name: go-lint
on: [push, pull_request]
jobs:
  golanci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          args: --enable-all --tests --out-format sarif ./... > golangci-lint.sarif

      - name: Show golangci-lint report
        run: cat golangci-lint.sarif

      - name: Upload golangci-lint report
        uses: actions/upload-artifact@v4
        with:
          name: golangci-lint report
          path: golangci-lint.sarif

  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gosec security scanner
        uses: securego/gosec@master
        with:
          args: -fmt sarif -out gosec.sarif ./...

      - name: Show gosec report
        run: cat gosec.sarif

      - name: Upload gosec report
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report
          path: gosec.sarif
